# Generated by Django 3.0.5 on 2020-04-10 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20200410_1111'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidat',
            name='status_email',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
