# Generated by Django 3.0.5 on 2020-04-10 22:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_candidat_status_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidat',
            name='Email',
            field=models.EmailField(default='Nouvelle', max_length=254),
        ),
    ]
