# Generated by Django 3.0.5 on 2020-04-10 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_auto_20200410_2251'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidat',
            name='etat',
            field=models.EmailField(default='Nouvelle', max_length=254),
        ),
        migrations.AlterField(
            model_name='candidat',
            name='Email',
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
